# Generated by Django 4.2.4 on 2025-08-01 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_itemcategory_url_alter_item_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('mobile', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_sean', models.BooleanField(default=False, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=200)),
                ('sub_title', models.CharField(default='NA', max_length=250)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('button_text', models.CharField(default='NA', max_length=250)),
                ('button_url', models.CharField(default='#', max_length=250)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
            },
        ),
    ]
