# Generated by Django 4.2.4 on 2023-09-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='url',
            field=models.CharField(default='NA', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
