# Generated by Django 4.2.4 on 2023-09-07 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='item/')),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
